# Generated by Django 3.0.8 on 2020-08-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200811_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airport',
        ),
    ]
