# Generated by Django 3.0.8 on 2020-08-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_delete_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
