# Generated by Django 3.0.8 on 2020-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20200814_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=64),
        ),
    ]
