# Generated by Django 3.0.8 on 2020-08-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20200814_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
