# Generated by Django 3.0.8 on 2020-08-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_delete_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airport',
        ),
    ]
