# Generated by Django 3.0.8 on 2020-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_auto_20200814_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('allflights', models.ManyToManyField(blank=True, related_name='passengers', to='flights.flight')),
            ],
        ),
    ]
