# Generated by Django 3.0.8 on 2020-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionlisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('currentbid', models.FloatField()),
                ('category', models.IntegerField(max_length=64)),
                ('image', models.URLField(max_length=1000)),
            ],
        ),
    ]
