# Generated by Django 3.0.8 on 2020-08-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='watchlist',
        ),
    ]
