# Generated by Django 3.0.8 on 2020-08-22 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200821_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenteditem', to='auctions.auctionlisting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentinguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
