# Generated by Django 3.0.8 on 2020-08-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistitem', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
